### ISSUE TITLE
可否再优化一下，实现visual模式下，移动光标直接跳转折叠部分

### ISSUE THREAD

**Issue by lfire** [xiyaowong/fast-cursor-move.nvim#1]
@xiyaowong 
![image](https://github.com/xiyaowong/fast-cursor-move.nvim/assets/2528719/d032bb6e-bbb9-441a-b270-2ae9c17b5c69)
像上图中的，在v模式下，也可以跳过折叠部分。
thx!

**Comment by xiyaowong** [comment]
弄不了的，跳过折叠部分需要使用vscode命令移动光标，在v-line, v-block模式下vscode的选中是模拟出来的，无法判断和保持选中范围。参考：https://github.com/vscode-neovim/vscode-neovim/issues/576#issuecomment-1835799743

**Comment by Jin-Whu** [comment]
> 弄不了的，跳过折叠部分需要使用vscode命令移动光标，在v-line, v-block模式下vscode的选中是模拟出来的，无法判断和保持选中范围。参考：[vscode-neovim/vscode-neovim#576 (comment)](https://github.com/vscode-neovim/vscode-neovim/issues/576#issuecomment-1835799743)

vscode-vim扩展的foldfix功能可以在visual模式下使用j，k键直接跳过折叠部分，并且选中了整个折叠区域，使用y键复制是整个折叠区域的代码，大佬能否实现呢
