### ISSUE TITLE
How can I configure the plugin?

### ISSUE THREAD

**Issue by dgokcin** [xiyaowong/fast-cursor-move.nvim#2]
Hello and thanks for this plugin.

I found this plugin after spending several hours on debugging why the j and k mapping to gj and gk was not functioning properly in vscode-neovim. I was wondering if it would be possible to disable/modify the acceleration behaviour. 

Thanks!

**Comment by AndreiMoraru123** [comment]
I'm not the author of the plugin, but it's made up of just one lua file. The way I see it, you could could fork it into your own and modify the behavior [around here](https://github.com/xiyaowong/fast-cursor-move.nvim/blob/main/plugin/fast-cursor-move.lua#L8)

**Comment by dgokcin** [comment]
@AndreiMoraru123 that is how I eventually ended up.

If anyone comes across to this, [here](https://github.com/xiyaowong/fast-cursor-move.nvim/compare/main...dgokcin:fast-cursor-move.nvim:main) are my change that allows you to use it as a plugin with an option to disable the acceleration behaviour. 

```lua
return {
  "dgokcin/fast-cursor-move.nvim",
  event = "BufRead",
  vscode = true,
  config = function()
      vim.defer_fn(function()
          require("fast-cursor-move").setup({
              enable_acceleration = false,
          })
      end, 500)
  end,
}

```
