### ISSUE TITLE
Doesn't work in visual mode

### ISSUE THREAD

**Issue by MikiVanousek** [xiyaowong/fast-cursor-move.nvim#3]
Hey, this is amazing. My only issue is that it does not work in visual mode. Did someone manage?

**Comment by xiyaowong** [comment]
Do you use vscode-neovim?

**Comment by MikiVanousek** [comment]
Yes, of course. Does this plugin work in visual mode for you?

**Comment by MikiVanousek** [comment]
Oh, my apologies. It works in visual mode, but not in `VISUAL BLOCK` mode.

**Comment by MikiVanousek** [comment]
It is the one you enter with `V`.

**Comment by xiyaowong** [comment]
Visual mode cannot be supported in vscode-neovim. The selected area of vscode-neovim is simulated. In short, the selected area is one-way synchronous.

**Comment by MikiVanousek** [comment]
But the visual mode (triggered with `v` as opposed to `V`) works with your extension. That makes me think visual block mode should be possible too.
